export const ROUTES = {
  home: "/",
  categories: "/categorias",
  login: "/login",
  register: "/registro",
  profile: "/perfil",
  services: "/servicios",
  map: "/mapa",
  dashboard: "/panel",
  settings: "/configuracion",
  messages: "/mensajes",
  products: "/productos",
  promotions: "/promociones",
  bankPromotions: "/promociones-bancarias",
  planPayment: "/plan",
  favorites: "/favoritos",
  professionalStore: "/perfil/:id/tienda",
  reels: "/reels",
};
