export const ROUTES = {
  home: "/",
  categories: "/categories",
  login: "/login",
  register: "/register",
  profile: "/profile",
  services: "/services",
  map: "/map",
  dashboard: "/dashboard",
  settings: "/settings",
  messages: "/messages",
  products: "/products",
  promotions: "/promotions",
  planPayment: "/plan/:planId",
  favorites: "/favorites",
};
